# Generated by Django 3.1.4 on 2021-01-05 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Set to true when the user have verified its email address', verbose_name='verified'),
        ),
    ]
