# Generated by Django 3.1.4 on 2021-01-02 23:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='created at')),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(blank=True, max_length=25)),
                ('identification', models.IntegerField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in the format: +999999999.', regex='\\+?1?\\d{9,15}$')])),
                ('email', models.EmailField(blank=True, error_messages={'unique': 'A user with that email already exists.'}, max_length=254, verbose_name='email address')),
                ('address', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=25)),
                ('reference', models.CharField(blank=True, max_length=50)),
                ('birthday', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-modified', '-created'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
    ]
