# Generated by Django 3.1.4 on 2021-01-07 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='cetegory',
            new_name='category',
        ),
    ]
